import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import fleetRouter from "./fleet";
import driversRouter from "./drivers";
import alertsRouter from "./alerts";
import setupRouter from "./setup";
import trainingRouter from "./training";
import platformRouter from "./platform";
import contactRouter from "./contact";
import telematicsRouter from "./telematics";
import geofencesRouter from "./geofences";
import behaviorRouter from "./behavior";
import maintenanceRouter from "./maintenance";
import dispatchRouter from "./dispatch";
import analyticsRouter from "./analytics";
import complianceRouter from "./compliance";
import integrationsRouter from "./integrations";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(fleetRouter);
router.use(driversRouter);
router.use(alertsRouter);
router.use(setupRouter);
router.use(trainingRouter);
router.use(platformRouter);
router.use(contactRouter);
router.use(telematicsRouter);
router.use(geofencesRouter);
router.use(behaviorRouter);
router.use(maintenanceRouter);
router.use(dispatchRouter);
router.use(analyticsRouter);
router.use(complianceRouter);
router.use(integrationsRouter);

export default router;
